### ISSUE TITLE
Printing out asd whenever getting total views

### ISSUE THREAD

**Issue by RoboSkyrat** [cavariux/twitchirc#1]
Whenever i call channel.getTotalViews() it prints asd.
is this some kind of debug?

**Comment by lmariscal** [comment]
I might think so, let me check the code and I will update it. Thanks by the way.
PD: Also if you can check if the isSub works cause I cant, thank you.

**Comment by lmariscal** [comment]
And yes, its a debug in the line '412' in the Channel class. I will remove it as soon as possible
