### ISSUE TITLE
Suggestion: Console

### ISSUE THREAD

**Issue by Squidkingdom** [cavariux/twitchirc#20]
It would be nice to have a console to interact with the bot directly. So if you said something to the console it sent a rawmessage to the IRC chat. It would be mainly nice to be able to stop the bot after running it without having to go into the Task Manager.

**Comment by mvarendorff** [comment]
In my honest oppinion this is not the task of the library. This library is supposed to open the opportunity to make something, providing all the necessary and useful functions.
Creating such a console would be something to do on your end I would say :)

**Comment by Squidkingdom** [comment]
ok
