### ISSUE TITLE
Can connect to discord

### ISSUE THREAD

**Issue by Squidkingdom** [cavariux/twitchirc#25]
I know that this is not what the bot is made for but is there a way to change some ip's and ports, and have it connect to Discord. I'm trying to use this library to make a cross platform bot and I need to know if its possible.

**Comment by lmariscal** [comment]
Hey, sorry to let you know but no, Discord is using a REST with HTTP api
for channels and other stuff (Not really familiar with Discord) and Twitch
is using IRC and they are two completly different communication protocols.
You can read more about how discord apps are developed in their oficial
doc: https://discordapp.com/developers/docs/intro

**Comment by Squidkingdom** [comment]
Thanks man

**Comment by mvarendorff** [comment]
@Squidkingdom If you are still interested in making a discord bot on its own, I can highly recommend the Java Wrapper for the discord API: [Discord4J](https://github.com/austinv11/Discord4J) :)
