### ISSUE TITLE
I have no clue whats going on its not connecting to channel or sending message

### ISSUE THREAD

**Issue by NiD27** [cavariux/twitchirc#29]
https://gyazo.com/a8edd38dab45a97f6e9d2dec0d37d7cc
https://gyazo.com/e9c0cdc329814d75af9a6540c8a94bc4

**Comment by mvarendorff** [comment]
Could not reproduce: 
![grafik](https://user-images.githubusercontent.com/26303198/35194734-60504348-feb8-11e7-8be4-54606b36c545.png)

Code is the basically the same you posted; just with a different name of the bot. The logger does not mention any errors and only confirms that you connected to the channel. There is nothing in your screenshot of the logs that shows the message sending but the code should do so.

If you are worried about the red text, that is perfectly fine and intended (maybe not the red color but that is how IntelliJ displays it). That is only the Logger doing its work so if you think that that is a massive error, it is not.

**Comment by NiD27** [comment]
@geisterfurz007  any idea why no message i just seen yourbot in my channel can you send me your code pls ill try that

**Comment by mvarendorff** [comment]
```
package com.cavariux.twitchirc;

import com.cavariux.twitchirc.Chat.Channel;

public class TestMain {
	
	public static void main(String[] args) {
		TestBot bot = new TestBot();
		bot.connect();
		Channel channel = bot.joinChannel("nidhish_a_n");
		bot.sendMessage("Hi, Im connected!", channel);
		bot.start();
	}

}
```
```
package com.cavariux.twitchirc;

import com.cavariux.twitchirc.Core.TwitchBot;

public class TestBot extends TwitchBot {

	public TestBot() {
		this.setUsername("MyUsername");
		this.setOauth_Key("MyOauthToken");
	}

}
```

**Comment by NiD27** [comment]
@geisterfurz007  thanks very much

**Comment by NiD27** [comment]
@geisterfurz007  you are the man bro got it working its was the start function that i needed to put in the last <3 thanks for help

**Comment by mvarendorff** [comment]
No problem! Enjoy coding and good luck!
