### ISSUE TITLE
Have some problems with userJoin method.

### ISSUE THREAD

**Issue by Esssse** [cavariux/twitchirc#33]
So i played around the userJoin. The problem is that the method is called 1-2 minutes after the user joined. 
```@Override
    protected void userJoins(User user, Channel channel) {
        this.whisper(user, "Type !help to get a list of commands.");
        this.sendMessage( user + ": Joined us", channel);
    }
```

**Comment by lmariscal** [comment]
The user join method is called by IRC JOIN, for some reason the twitch chat doesn't send a signal as soon as a user joins, making this dumb delay. Sadly there's nothing we can do as the Twitch Api doesn't support this natively.
