### ISSUE TITLE
How to import library and use classes?

### ISSUE THREAD

**Issue by JaimeAranSoto** [cavariux/twitchirc#6]
Sorry if it is a obvious question.
I'm using NetBeans and i added the jar file to project libaries, but the program still don't recognize classes and 'import' feature doesn't work.
There is no construcot of TwitchBot? i have to change the username, oauth, by methods? .-.

**Comment by lmariscal** [comment]
I'm not used to work with NetBeans but here I found a video that shows you how to add a Jar file to your project: [https://youtu.be/jsS_cRbNv3o?t=59s](https://youtu.be/jsS_cRbNv3o?t=59s)
If you want tutorials on how to use this library check the [**wiki**](https://github.com/CavariuX/TwitchIRC/wiki). 
Also this project is unmaintained (But please don't get discourage this library should still be working just that no features are being developed) and if you want to actually add new features you are free to fork it and make your changes.
Happy to help with any other problem.
